// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import java.util.Scanner;

/************************************************************/
/**
 * 
 */
public class Partida {
	/**
	 * 
	 */
	public Horca horca;
	/**
	 * 
	 */
	public Palabra palabra;

	/**
	 * Muestra el estado de la horca y los resultados de palabra
	 */
	public void mostrarProgreso() {
		horca.dibujar();
		palabra.mostrarResultados();
	}

	/**
	 * Solicita una letra al usuario
	 * 
	 * @return letra
	 */
	public char pedirLetra() {
		Scanner entrada = new Scanner(System.in);
		System.out.print("Introduce una letra: ");
		char letra = entrada.nextLine().charAt(0);

		return letra;

	}

	/**
	 * Pide la respuesta y devuelve true si era la que buscabamos
	 * 
	 * @return palabra true si era la que busabamos o false en caso contrario
	 */
	public boolean resolver() {

		Scanner entrada = new Scanner(System.in);
		System.out.print("Introduce una letra: ");
		return palabra.comprobarPalabra(entrada.nextLine());

	}

	/**
	 * Comprueba tanto si hemos agotado los fallos como si hemos acertado todas
	 * las letras
	 * 
	 * @return fin
	 */
	public boolean comprobarFinal() {

	}

	public static void main(String[] args) {

	}
}
